# Generated by Django 4.2.9 on 2025-07-14 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='description_long',
            new_name='long_description',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='description_short',
            new_name='short_description',
        ),
        migrations.RemoveField(
            model_name='place',
            name='slug',
        ),
    ]
