# Generated by Django 4.2.9 on 2025-07-15 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_alter_image_image_alter_place_long_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='number',
            field=models.PositiveIntegerField(default=1, verbose_name='Номер фото'),
        ),
    ]
