# Generated by Django 4.2.9 on 2025-07-17 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_alter_image_options_alter_image_number'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['number'], name='places_imag_number_b0addc_idx'),
        ),
    ]
