# Generated by Django 4.2.1 on 2025-07-09 11:50

from django.db import migrations, models
import places.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_alter_place_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default='places/static/places/img/no_image.jpg', upload_to=places.models.get_directory_path, verbose_name='Фото'),
        ),
    ]
