# Generated by Django 4.2.9 on 2025-07-17 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_image_places_imag_number_b0addc_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='number',
            field=models.PositiveIntegerField(default=0, verbose_name='Номер фото'),
        ),
    ]
