# Generated by Django 4.2.1 on 2025-07-10 13:02

from django.db import migrations, models
import places.models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default='', upload_to=places.models.get_directory_path, verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='place',
            name='description_long',
            field=tinymce.models.HTMLField(verbose_name='Подробное описание'),
        ),
    ]
